language: android

android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

notifications:
  email: false

jdk: oraclejdk7

sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/2.12
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

script:
  - ./gradlew checkstyle build --continue --stacktrace
