language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
addons:
  apt_packages:
    - pandoc

notifications:
  email: false

jdk: oraclejdk7

sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/2.10
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

script:
  - ./gradlew checkstyle build --continue --stacktrace

after_failure:
  - pandoc simplekeyvaluestorage/build/outputs/lint-results.html -t plain